services:
  - type: web
    name: parcelvoy
    env: docker
    repo: https://github.com/parcelvoy/platform.git
    branch: 'render'
    dockerfilePath: ./docker/Dockerfile.render
    dockerContext: .
    autoDeploy: false
    healthCheckPath: /api/health
    envVars:
      - fromGroup: platform
  - type: redis
    name: lightning
    ipAllowList: []
    plan: free # optional (defaults to starter instance type)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

databases:
  - name: database
    databaseName: parcelvoy
    ipAllowList: [] # only allow internal connections

envVarGroups:
  - name: platform
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        fromDatabase:
          name: prod
          property: host
      - key: DB_USERNAME
        fromDatabase:
          name: prod
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: prod
          property: password
      - key: DB_PORT
        fromDatabase:
          name: prod
          property: post
      - key: DB_DATABASE
        value: parcelvoy
      - key: STORAGE_DRIVER
        value: local
      - key: QUEUE_DRIVER
        value: redis
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - key: AUTH_DRIVER
        value: local
      - key: AUTH_BASIC_EMAIL
        sync: false
      - key: AUTH_BASIC_PASSWORD
        sync: false