name: Publish Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-package:
    name: "Publish to GitHub Packages"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'parcelvoy'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run package:publish --tag=$(echo ${GITHUB_REF_NAME:1})
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}